[package]
name = "zalo-app"
version.workspace = true
edition.workspace = true
authors.workspace = true
description = "Application binary for the Zalo bot platform"
license.workspace = true

[dependencies]
zalo-core = { path = "../core" }
tracing.workspace = true
tracing-subscriber.workspace = true
