[package]
name = "bot-axum"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
publish = false

[dependencies]
axum.workspace = true
bytes = "1"
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
serde.workspace = true
serde_json.workspace = true
zalo-http.workspace = true
zalo-bot.workspace = true
zalo-types.workspace = true
tower-http.workspace = true
config.workspace = true
